### ISSUE TITLE
Rake tests fail on 1.9.2

### ISSUE THREAD

**Issue by parndt** [shwoodard/active_assets#1]
Just switch into ruby 1.9.2 and run the tests, 25% pass.  Mainly due to:

```
ArgumentError: Unknown key(s): type, expansion_name, group
/Users/parndt/.rvm/gems/ruby-1.9.2-p136/gems/activesupport-3.0.3/lib/active_support/core_ext/hash/keys.rb:43:in `assert_valid_keys'
/code/active_assets/lib/active_assets/active_expansions/expansion.rb:27:in `asset'
/code/active_assets/lib/active_assets/active_expansions/expansions.rb:42:in `block in asset'
/code/active_assets/lib/active_assets/active_expansions/expansion.rb:21:in `instance_eval'
/code/active_assets/lib/active_assets/active_expansions/expansion.rb:21:in `configure'
/code/active_assets/lib/active_assets/active_expansions/expansions.rb:41:in `asset'
/code/active_assets/test/fixtures/rails_root/config/assets/assets.rb:9:in `block (3 levels) in <top (required)>'
```

**Comment by parndt** [comment]
Just a note that it's not just the tests, you can't start rails server under 1.9.2 with this library enabled due to the same error :)

**Comment by parndt** [comment]
I've looked into this and can't find why/where it's working for 1.8.7 and not for 1.9.2

**Comment by shwoodard** [comment]
This is fixed in master

**Comment by parndt** [comment]
Amazing, such a small thing. 

Thanks Sam!
